from config.db import get_connection
from datetime import datetime


def get_simulation_metadata(simulation_id):
    conn = get_connection()
    cursor = conn.cursor()
    
    query = """
        SELECT * FROM Simulation WHERE Simulation_Id = ?
    """
    
    cursor.execute(query, (simulation_id,))
    row = cursor.fetchone()

    if row:
        return {
            'Simulation_Id': row.Simulation_Id,
            'Simulation_Name': row.Simulation_Name,
            'Created_At': str(row.Created_At),
            'Status': row.Status,
            'Computational_Time': row.Computational_Time,
            'Evaluation_Id': row.Evaluation_Id,
        }
    else:
        return None
    
def get_simulation_evacuees(simulation_id):
    conn = get_connection()
    cursor = conn.cursor()
    query = """
        SELECT * FROM Evacuees WHERE Simulation_Id =?
    """

    cursor.execute(query, (simulation_id,))
    rows = cursor.fetchall()

    evacuees = []
    for row in rows:
        evacuees.append({
            'Evacuee_Id': row.evacuee_id,
            'Simulation_Id': row.simulation_id,
            'Latitude': row.latitude,
            'Longitude': row.longitude,
            'Z': row.z,
        })

    return evacuees

def get_simulation_hazards(simulation_id):
    conn = get_connection()
    cursor = conn.cursor()
    query = """
        SELECT * FROM Hazards WHERE Simulation_Id =?
    """

    cursor.execute(query, (simulation_id,))
    rows = cursor.fetchall()

    hazards = []
    for row in rows:
        hazards.append({
            'Hazard_Id': row.Hazard_Id,
            'Simulation_Id': row.Simulation_Id,
            'Hazard_Type': row.Hazard_Type,
            'Latitude': row.Latitude,
            'Longitude': row.Longitude,
            'Z': row.Z,
            'Step_Order': getattr(row, 'Step_Order', 0) or 0
        })
        print("hazard", hazards)

    return hazards

def get_evacuees_route(evacuees_id):
    conn = get_connection()
    cursor = conn.cursor()
    query = """
        SELECT * FROM ROUTE_POINT WHERE Evacuee_Id =?
    """

    cursor.execute(query, (evacuees_id,))
    rows = cursor.fetchall()
    # print("rows", rows)
    route = []
    for row in rows:
        route.append({
            'Route_Point_Id': row.Route_Point_Id,
            'Evacuee_Id': row.Evacuee_Id,
            'Latitude': row.Latitude,
            'Longitude': row.Longitude,
            'Z': row.Z,
            'Step_Order': row.Step_Order,
        })
    
    
    return {'route': route}


def create_custom_sim(user_id, simulation_name, status, computational_time=1000, evaluation_id=None):
    conn = get_connection()
    cursor = conn.cursor()

    query = """
        INSERT INTO Simulation (User_Id, Simulation_Name, Created_At, Status, Computational_Time, Evaluation_Id)
        OUTPUT INSERTED.Simulation_Id
        VALUES (?, ?, ?, ?, ?, ?)
    """

    timestamp = datetime.now()  # current time

    cursor.execute(query, (user_id, simulation_name, timestamp, status, computational_time, evaluation_id))
    
    # fetch the autogenerated simulation_id
    simulation_id = cursor.fetchone()[0]
    print("simulation id from database:", simulation_id)
    
    conn.commit()
    cursor.close()
    conn.close()
    
    return {
        "message": "Simulation created successfully",
        "simulation_id": simulation_id
    }


def save_evacuees(simulation_id, evacuees_data):
    conn = get_connection()
    cursor = conn.cursor()
    
    query = """
    INSERT INTO evacuees (simulation_id, latitude, longitude, z)
    OUTPUT INSERTED.evacuee_id
    VALUES (?, ?, ?, ?)
    """

    evacuee_ids = []

    for data in evacuees_data:
        cursor.execute(query, (simulation_id, data['latitude'], data['longitude'], data['z']))
        evacuee_id = cursor.fetchone()[0]  # this now works, since OUTPUT returns a row
        evacuee_ids.append({
            "evacuee_id": evacuee_id,
            "latitude": data['latitude'],
            "longitude": data['longitude'],
            "z": data['z']
        })

    conn.commit()
    cursor.close()
    conn.close()

    return evacuee_ids


def save_hazards(simulation_id, hazards_data):
    conn = get_connection()
    cursor = conn.cursor()
    
    query = """
        INSERT INTO Hazards (Simulation_Id,Hazard_Type, Latitude, Longitude, Z, Step_Order)
        VALUES (?,?,?,?,?,?)
    """
    
    for data in hazards_data:
        step_order = data.get('step_order') or 0
        print("step order", step_order)
        cursor.execute(query, (simulation_id, data['hazard_type'], data['latitude'], data['longitude'], data['z'], step_order))
        
    conn.commit()
    cursor.close()
    conn.close()

    return {"message": "Hazards saved successfully"}
    
def save_route_points_bulk(evacuee_id, points):
    conn = get_connection()
    cursor = conn.cursor()
    cursor.fast_executemany = True
    query = """
        INSERT INTO ROUTE_POINT (Evacuee_Id, Latitude, Longitude, Z, Step_Order)
        VALUES (?,?,?,?,?)
    """

    # Build list of tuples for executemany
    data = [(evacuee_id, lat, lon, z, step_order) for (lon, lat, z, step_order) in points]

    cursor.executemany(query, data)

    conn.commit()
    cursor.close()
    conn.close()

    return {"message": f"{len(points)} route points saved successfully"}

def save_route_point(evacuees_id, longitude, latitude, z, step_order):
    conn = get_connection()
    cursor = conn.cursor()
    
    query = """
        INSERT INTO ROUTE_POINT (Evacuee_Id, Latitude, Longitude, Z, Step_Order)
        VALUES (?,?,?,?,?)
    """
    
    cursor.execute(query, (evacuees_id, latitude, longitude, z, step_order))

    conn.commit()
    cursor.close()
    conn.close()

    return {"message": "Route point saved successfully"}

def get_evacuees_position(evacuee_id, current_step):
    conn = get_connection()
    cursor = conn.cursor()
    query = """
        SELECT Latitude, Longitude, Z FROM ROUTE_POINT WHERE Evacuee_Id = ? AND Step_Order = ?
    """

    cursor.execute(query, (evacuee_id, current_step))
    rows = cursor.fetchone()

    evacuees_position = rows or None
    print("evacuees position current step", evacuees_position, current_step, evacuee_id)

    cursor.close()
    conn.close()

    return evacuees_position

def remove_route_points(evacuee_id, step_order):
    conn = get_connection()
    cursor = conn.cursor()  
    
    query = """
        DELETE FROM ROUTE_POINT WHERE Evacuee_Id = ? AND Step_Order > ?
    """
    
    cursor.execute(query, (evacuee_id, step_order))

    conn.commit()
    cursor.close()
    conn.close()

    return {"message": "Route point deleted successfully"}